[tasks.stow]
description = "Create symlinks for configuration files"
run = "stow --verbose --target=$HOME --restow */"

[tasks.unstow]
description = "Remove symlinks created by stow"
run = "stow --verbose --target=$HOME --delete */"

[tasks.delete]
description = "Delete default shell config files"
run = "rm ~/.zshrc ~/.bashrc"
hide = true
